### ISSUE TITLE
Drop Box Updates and a Few New Features

### ISSUE THREAD

**Issue by aembler** [concrete5/drop_box#6]
- The tus command that we have allows a command line worker to be run periodically to clear out old uploads. Can you make sure this works? It would also be really great if we could run it via some kind of console command that was registered in our package, so we didn't have to pass in configuration information.
- When I tested upload resuming, it totally worked, which was great. However one time when my upload stalled and I got logged out, when I logged back in and resumed my upload it didn't work. Could you check this yourself? It's possible this was a momentary hiccup, but if it's not, is there any way we could make this even more robust? Thoughts?
- When deleting a file from the drop box, it didn't delete the underlying concrete5 file. Can you make this work? It needs to delete the concrete5 file, which should remove the file from the filesystem, remove all versions, etc....
- Can you add "View Details" to the drop box menu, which takes you over to the file manager details screen. It's the same one you can get to by clicking on the filename of a file in the file manager.
- Sorting files in the dropbox doesn't seem to work.
- Bulk delete doesn't work in the dropbox interface. Can you make it work and make it look like the file manager's bulk delete dialog?
- At this point I've reworked file permissions and just made the permission for whether a user can add to a dropbox into an admin task permission, which doesn't take an object. That means we don't need a file object in order to check the permissions of whether they can add to the dropbox. Can you rework the upload routine so that it checks permissions first, and only imports the file into concrete5 if the user has the permission to upload to the dropbox?
- When installing the Dropbox add-on, can you create a "Drop Box" file folder in the file manager at the top level?
- Dropbox Frontend: Can you add a folder chooser using the `Concrete\Core\Form\Service\Widget\FileFolderSelector` widget to the block, and default it to the "Drop Box" folder I just mentioned? The selector should also let the user select their own custom folder to upload into.
- Can you add a new option to the dropbox block that is:

"Upload Complete Complete Response"

and a textarea that lets the admin enter the text that should be shown to the user when the file uploads successfully.

- Add another field to the drop box block that is

[] Display URL to Uploaded File

This is a checkbox field that admins can check. If checked, when a user uploads a file, they should receive the permalink to the file. Just use the getDownloadURL() method on the file (which should route it through the download_file/ single page, I believe).

This use case is for sites that want to provide a drop box to their users, and then allow their users to use the site to host the file while they provide it for someone else. Believe it or not this is actually the use case that our client wants (go figure.)

**Comment by aembler** [comment]
I've merged in your updates, and I can see that some changes are made, but I don't think the success is working as well as it could be.

Can you do the following:

1. When uploads are complete, can you close the Tus window?
2. When uploads are complete, can you open a new bootstrap modal that says Success, and displays the upload complete message?
3. In this window, can you add the URL if the display URL to uploaded file is active? Right now things are kind of confusing, and the URL to the uploaded file isn't displaying:

<img width="1351" alt="Screen Shot 2020-10-26 at 10 52 40 AM" src="https://user-images.githubusercontent.com/527809/97209453-98626900-1779-11eb-83b3-fa17442257b3.png">

**Comment by bitterdev** [comment]
https://github.com/concrete5/drop_box/pull/9
